title: ielab
description: Information Engineering Lab
google_analytics:
show_downloads: false
logo: /images/ielab-page001.png

paginate: 5
paginate_path: "/posts/page-:num/"

plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  projects:
    output: true
  people:
    people: true
    output: true
  publications:
    output: true
  tutorials:
    output: true
  grants:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: projects
  - scope:
      path: ""
      type: "people"
    values:
      layout: people
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publications
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: tutorials
  - scope:
      path: ""
      type: "grants"
    values:
      layout: grants
